"""
Author: Josiah Buxton
Description: Helper function to convert a public key to a format which
can be inserted into a C program
"""

cert = "-----BEGIN CERTIFICATE----- \n\
MIIFtzCCBJ+gAwIBAgIQZYgPVab72N0FAAAAAIgIBDANBgkqhkiG9w0BAQsFADBC \n\
MQswCQYDVQQGEwJVUzEeMBwGA1UEChMVR29vZ2xlIFRydXN0IFNlcnZpY2VzMRMw \n\
EQYDVQQDEwpHVFMgQ0EgMU8xMB4XDTIxMDcxMjAzNTYzOVoXDTIxMTAwNDAzNTYz \n\
OFowbTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcT \n\
DU1vdW50YWluIFZpZXcxEzARBgNVBAoTCkdvb2dsZSBMTEMxHDAaBgNVBAMTE21x \n\
dHQuZ29vZ2xlYXBpcy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB \n\
AQDwXjLumgn2xMAQDgDQ2OyeRMKw5BPyQQaJ25rESSFIEYF6kL26xp8i2HQP8GvX \n\
zsJ1gVEN3OOVAsfENvZT+P/6G77OvxMDFNwyfjz/79+TnW3Ow8zp6Orlgzq+fNCw \n\
1IHAFlem8hnYpZS3MWV4b4dhjQNwUAzVGMIOuQcoV+ouC4vFHDAl0bVqkaMYvLqS \n\
Wc5QdoPCncI8QEJkgLETduBvOwaqEN6usDo5ZiHLnMnoFiXFXrVKQl/F40F/2cr7 \n\
9LwLifve1bBT2+dQJrfc5L/pLNvkIrF5/1qCyGIes5DLNUKfqamxxBjiq/GJ56xu \n\
IQq0qLSdJZOTrNeApqsGR2PBAgMBAAGjggJ8MIICeDAOBgNVHQ8BAf8EBAMCBaAw \n\
EwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUhb4F \n\
ZT4ytT5nxzDg7n7s8y6BmzAwHwYDVR0jBBgwFoAUmNH4bhDrz5vsYJ8YkBug630J \n\
/SswaAYIKwYBBQUHAQEEXDBaMCsGCCsGAQUFBzABhh9odHRwOi8vb2NzcC5wa2ku \n\
Z29vZy9ndHMxbzFjb3JlMCsGCCsGAQUFBzAChh9odHRwOi8vcGtpLmdvb2cvZ3Ny \n\
Mi9HVFMxTzEuY3J0MDgGA1UdEQQxMC+CE21xdHQuZ29vZ2xlYXBpcy5jb22CGG1x \n\
dHQtbXRscy5nb29nbGVhcGlzLmNvbTAhBgNVHSAEGjAYMAgGBmeBDAECAjAMBgor \n\
BgEEAdZ5AgUDMDMGA1UdHwQsMCowKKAmoCSGImh0dHA6Ly9jcmwucGtpLmdvb2cv \n\
R1RTMU8xY29yZS5jcmwwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdwDuwJXujXJk \n\
D5Ljw7kbxxKjaWoJe0tqGhQ45keyy+3F+QAAAXqZEwrFAAAEAwBIMEYCIQCdox1E \n\
p2wIOfdwsiY0icOi9EIlwPuyRnnbAFb/4BsARQIhAOwN2zfDNpU8oMHB4cHBfnJw \n\
eij2AkVfPUYVoJ/fCkuXAHYA9lyUL9F3MCIUVBgIMJRWjuNNExkzv98MLyALzE7x \n\
ZOMAAAF6mRMKrAAABAMARzBFAiByJoceg0N6i0GKw8y9Ez7EGdKY62o/3lKnIqnx \n\
Z+bjzwIhAJIVaQgOknUEJ837HiYKYe9BtRn29SqvnFvpAvjHd3ShMA0GCSqGSIb3 \n\
DQEBCwUAA4IBAQBVbwVyVrKDKHu2X3Qu9C2OULgF6f0ocVAkPn+0NrkzpyRHn+5W \n\
96QNg4XDjnd71V4ok6uZChxuCdnRQiLMyLTQWAW2Xk1SmgslWLu5buuJx8+hpOuV \n\
LS0gvov309/vaQb+5a7CD5SLRxocPfH5dnIHXxvTOR+0LKgwPt7Hc2egtX5RvWmq \n\
te3qNjkwhV4irOGflCeSdk/7eOJUVe2B7Q+EByNpoWrb+3Dogqju0cX0oFFZib6w \n\
DWEszX2ErUwFpH4GCsuaJod4SllXQMvbN+JaOHI32+E85tldnN7MKHKJfSarfW6M \n\
HM66HdWQytga+onc2RVqCRYwQQwQrcdqgNzP \n\
-----END CERTIFICATE-----"

split_cert = cert.split(' \n')
output = ""
for i, hex_num in enumerate(split_cert):
  output += f"\t\"{hex_num}\\n\" \n"
print(output)