export const DATA_PREV_SCREEN_UPDATE = '[DATA] PREV_SCREEN_UPDATE';
export const DATA_RESET = '[DATA] RESET';
export const DATA_ACTIVE_SCREEN_UPDATE = '[DATA] ACTIVE_SCREEN_UPDATE';
export const DATA_UPDATE_PRODUCTS = '[DATA] UPDATE_PRODUCTS';
